# Generated by Django 4.1 on 2025-05-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_card_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Student Photo'),
        ),
    ]
